name: github-actions-test
on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때

jobs:
  My-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: 첫 번째 메시지 출력
        run: echo "Hello, world!"

      - name: 두 번째 메시지 출력
        run: echo "This is the second step."

      - name: 세 번째 메시지 출력
        run: echo "CI/CD 테스트 중입니다."

      - name: 네 번째 메시지 출력
        run: echo "모든 스텝이 정상 작동 중!"
# name: NestJS CI 테스트

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: 저장소 코드 체크아웃
#         uses: actions/checkout@v3

#       - name: Node.js 세팅 (v18)
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: 의존성 설치
#         run: npm install

#       - name: NestJS 빌드
#         run: npm run build

#       - name: 테스트 실행
#         run: npm run test -- --watch=false --bail
