name: github-actions-test
on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때

jobs: # 하나의 job은 여러 개의 step으로 구성됨
  My-first-job:
    runs-on: ubuntu-latest # 최신 우분투 환경에서 실행

    steps:
      - name: Hello world
        run: echo "Hello, world!" # Hello, world! 출력

# name: CI / CD 예제
#출력

# on:
#   push:
#     branches:
#       - main  # main 브랜치에 푸시될 때

# jobs: # 하나의 job은 여러 개의 step으로 구성됨
#   Deploy:
#     runs-on: ubuntu-latest # 최신 우분투 환경에서 실행

#     steps:
#       - name: Checkout code
#         uses: appleboy/ssh-action@v1.0.3

#       - name: Build and Deploy
#         run: |
#           echo "코드 빌드 및 배포 작업 수행"
#           # 여기에 실제 빌드 및 배포 명령어를 추가하세요.
